# Generated by Django 5.2.8 on 2025-11-16 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='stock_minimo',
            field=models.IntegerField(default=5, help_text='Stock mínimo para alertas'),
        ),
    ]
