# Generated by Django 5.2.8 on 2025-11-17 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('inventario', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_devolucion', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('defecto', 'Producto Defectuoso'), ('error', 'Error en la Venta'), ('cliente', 'Solicitud del Cliente'), ('garantia', 'Garantía'), ('otro', 'Otro Motivo')], max_length=20)),
                ('descripcion_motivo', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], db_index=True, default='pendiente', max_length=20)),
                ('observaciones_aprobacion', models.TextField(blank=True)),
                ('usuario_aprueba', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('usuario_solicita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo_especifico', models.TextField(blank=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('devolucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion')),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devoluciones',
                'db_table': 'detalle_devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('codigo_ticket', models.IntegerField(unique=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tipo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('mixto', 'Pago Mixto')], max_length=20)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], db_index=True, default='pendiente', max_length=20)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_finalizacion', models.DateTimeField(blank=True, null=True)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ticket',
                'verbose_name_plural': 'Tickets',
                'db_table': 'tickets',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DetalleTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('activo', models.BooleanField(default=True)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.ticket')),
            ],
            options={
                'db_table': 'detalle_tickets',
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tipo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('mixto', 'Pago Mixto')], max_length=50)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('codigo_venta', models.IntegerField(unique=True)),
                ('estado', models.IntegerField(default=1)),
                ('estado_venta', models.IntegerField(choices=[(0, 'Anulado'), (1, 'Pendiente'), (2, 'Pagado')], default=1)),
                ('es_pago_mixto', models.BooleanField(default=False)),
                ('monto_efectivo', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado en efectivo (pago mixto)', max_digits=10)),
                ('monto_tarjeta', models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado con tarjeta (pago mixto)', max_digits=10)),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('descuento_monto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='venta',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_original', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nota', models.CharField(db_index=True, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_utilizacion_completa', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('aplicada', 'Aplicada Parcialmente'), ('utilizada', 'Utilizada Completamente'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='emitida', max_length=20)),
                ('devolucion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='ventas.devolucion')),
                ('venta_original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'notas_credito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.venta'),
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.IntegerField(default=1)),
                ('producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Ventas',
                'db_table': 'detalle_ventas',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('venta_crear', 'Crear Venta'), ('venta_anular', 'Anular Venta'), ('venta_modificar', 'Modificar Venta'), ('devolucion_crear', 'Crear Devolución'), ('devolucion_aprobar', 'Aprobar Devolución'), ('devolucion_rechazar', 'Rechazar Devolución'), ('devolucion_procesar', 'Procesar Devolución'), ('nota_credito_emitir', 'Emitir Nota Crédito'), ('nota_credito_aplicar', 'Aplicar Nota Crédito'), ('cierre_caja', 'Cierre de Caja'), ('ticket_crear', 'Crear Ticket'), ('ticket_finalizar', 'Finalizar Ticket'), ('ticket_cancelar', 'Cancelar Ticket'), ('producto_crear', 'Crear Producto'), ('producto_modificar', 'Modificar Producto'), ('stock_ajustar', 'Ajustar Stock')], db_index=True, max_length=50)),
                ('descripcion', models.TextField()),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.devolucion')),
                ('venta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Auditoría de Movimiento',
                'verbose_name_plural': 'Auditoría de Movimientos',
                'db_table': 'auditoria_movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='AplicacionNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
                ('nota_credito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='ventas.notacredito')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_aplicadas', to='ventas.venta')),
            ],
            options={
                'verbose_name': 'Aplicación de Nota de Crédito',
                'verbose_name_plural': 'Aplicaciones de Notas de Crédito',
                'db_table': 'aplicaciones_notas_credito',
            },
        ),
        migrations.CreateModel(
            name='CierreCaja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('monto_inicial', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cantidad_ventas', models.IntegerField(default=0)),
                ('efectivo_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('debito_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('credito_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transferencia_ventas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('egresos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('detalle_egresos', models.TextField(blank=True)),
                ('monto_final_esperado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('monto_final_real', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cierres_caja',
                'unique_together': {('fecha', 'usuario')},
            },
        ),
    ]
