# Generated by Django 5.2.8 on 2025-11-16 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_tickets_cierrecaja'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_estado_55d03b_idx',
            old_name='tickets_estado_usuario_idx',
        ),
        migrations.RenameIndex(
            model_name='ticket',
            new_name='tickets_fecha_c_22ac59_idx',
            old_name='tickets_fecha_creacion_idx',
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('mercadopago', 'Mercado Pago')], max_length=50),
        ),
    ]
