# Generated by Django 5.2.8 on 2025-11-17 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0002_agregar_turno_cierrecaja'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={'verbose_name': 'Cierre de Caja', 'verbose_name_plural': 'Cierres de Caja'},
        ),
    ]
