# Generated by Django 5.2.8 on 2025-11-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ventas', '0003_rename_tickets_estado_usuario_idx_tickets_estado_55d03b_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='es_pago_mixto',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado en efectivo', max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado con tarjeta', max_digits=10),
        ),
    ]
