# Generated by Django 5.2.8 on 2025-11-17 01:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0002_producto_stock_minimo'),
        ('ventas', '0004_venta_es_pago_mixto_venta_monto_efectivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionNotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_aplicacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Aplicación de Nota de Crédito',
                'verbose_name_plural': 'Aplicaciones de Notas de Crédito',
                'db_table': 'aplicaciones_notas_credito',
            },
        ),
        migrations.CreateModel(
            name='AuditoriaMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('venta_crear', 'Crear Venta'), ('venta_anular', 'Anular Venta'), ('venta_modificar', 'Modificar Venta'), ('devolucion_crear', 'Crear Devolución'), ('devolucion_aprobar', 'Aprobar Devolución'), ('devolucion_rechazar', 'Rechazar Devolución'), ('devolucion_procesar', 'Procesar Devolución'), ('nota_credito_emitir', 'Emitir Nota Crédito'), ('nota_credito_aplicar', 'Aplicar Nota Crédito'), ('cierre_caja', 'Cierre de Caja'), ('ticket_crear', 'Crear Ticket'), ('ticket_finalizar', 'Finalizar Ticket'), ('ticket_cancelar', 'Cancelar Ticket'), ('producto_crear', 'Crear Producto'), ('producto_modificar', 'Modificar Producto'), ('stock_ajustar', 'Ajustar Stock')], db_index=True, max_length=50)),
                ('descripcion', models.TextField()),
                ('datos_json', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('fecha', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'verbose_name': 'Auditoría de Movimiento',
                'verbose_name_plural': 'Auditoría de Movimientos',
                'db_table': 'auditoria_movimientos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DetalleDevolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_producto', models.CharField(max_length=500)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('motivo_especifico', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Detalle de Devolución',
                'verbose_name_plural': 'Detalles de Devoluciones',
                'db_table': 'detalle_devoluciones',
            },
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_devolucion', models.CharField(max_length=20, unique=True)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_procesamiento', models.DateTimeField(blank=True, null=True)),
                ('motivo', models.CharField(choices=[('defecto', 'Producto Defectuoso'), ('error', 'Error en la Venta'), ('cliente', 'Solicitud del Cliente'), ('garantia', 'Garantía'), ('otro', 'Otro Motivo')], max_length=20)),
                ('descripcion_motivo', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada'), ('procesada', 'Procesada')], db_index=True, default='pendiente', max_length=20)),
                ('observaciones_aprobacion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Devolución',
                'verbose_name_plural': 'Devoluciones',
                'db_table': 'devoluciones',
                'ordering': ['-fecha_solicitud'],
            },
        ),
        migrations.CreateModel(
            name='NotaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_nota', models.CharField(db_index=True, max_length=20, unique=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('saldo_disponible', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_utilizacion_completa', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('emitida', 'Emitida'), ('aplicada', 'Aplicada Parcialmente'), ('utilizada', 'Utilizada Completamente'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], db_index=True, default='emitida', max_length=20)),
            ],
            options={
                'verbose_name': 'Nota de Crédito',
                'verbose_name_plural': 'Notas de Crédito',
                'db_table': 'notas_credito',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.AlterModelOptions(
            name='cierrecaja',
            options={},
        ),
        migrations.AlterModelOptions(
            name='detalleticket',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_estado_55d03b_idx',
        ),
        migrations.RemoveIndex(
            model_name='ticket',
            name='tickets_fecha_c_22ac59_idx',
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venta',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venta',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='detalleticket',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='detalleticket',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descuento_monto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='descuento_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado en efectivo (pago mixto)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='monto_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto pagado con tarjeta (pago mixto)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='tipo_pago',
            field=models.CharField(choices=[('efectivo', 'Efectivo'), ('debito', 'Tarjeta de Débito'), ('credito', 'Tarjeta de Crédito'), ('transferencia', 'Transferencia'), ('mixto', 'Pago Mixto')], max_length=50),
        ),
        migrations.AddField(
            model_name='aplicacionnotacredito',
            name='venta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_aplicadas', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='auditoriamovimiento',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='auditoriamovimiento',
            name='venta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='producto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventario.producto'),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario_aprueba',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_aprobadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='usuario_solicita',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devoluciones_solicitadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='devolucion',
            name='venta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='detalledevolucion',
            name='devolucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='ventas.devolucion'),
        ),
        migrations.AddField(
            model_name='auditoriamovimiento',
            name='devolucion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ventas.devolucion'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='devolucion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nota_credito', to='ventas.devolucion'),
        ),
        migrations.AddField(
            model_name='notacredito',
            name='venta_original',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notas_credito', to='ventas.venta'),
        ),
        migrations.AddField(
            model_name='aplicacionnotacredito',
            name='nota_credito',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='ventas.notacredito'),
        ),
    ]
